sudo: false

language: python

python:
  - '3.6.6'

addons:
  postgresql: "9.5"
  apt:
    packages:
      - postgresql-9.5-postgis-2.3

cache:
  directories:
    - $HOME/.cache/pip

before_cache:
  - rm -f $HOME/.cache/pip/log/debug.log

install:
  - pip install -r requirements/local.txt
  - pip install codecov

before_script:
  - export DATABASE_URL=postgres://postgres@localhost/standup
  - psql -c "CREATE DATABASE standup;" -U postgres

script:
  - flake8
  - pytest --cov -v --tb=native

after_success:
  - codecov
